In [6]:
#--import block--
import pandas as pd
import numpy as np
#!pip install scikit-learn
from sklearn import preprocessing
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split

In [7]:
#--raw data--
data_orig = pd.read_csv('housepricedata.csv')
#print(data_orig)
X_orig = data_orig.iloc[:,0:10].values
Y_orig = data_orig.iloc[:,10].values
print(X_orig,Y_orig)
#train_orig, test_orig = np.split(data_orig,[int(.8*len(data_orig))])
#print(train_orig)

[[ 8450     7     5 ...     8     0   548]
 [ 9600     6     8 ...     6     1   460]
 [11250     7     5 ...     6     1   608]
 ...
 [ 9042     7     9 ...     9     2   252]
 [ 9717     5     6 ...     5     0   240]
 [ 9937     5     6 ...     6     0   276]] [1 1 1 ... 1 0 0]


In [8]:
#--train and test data(80:20)--
X_train, X_test, Y_train, Y_test = train_test_split(X_orig, Y_orig, test_size=0.2)
#X_train = train_orig.iloc[:,0:10].values
#Y_train = train_orig.iloc[:,10].values
#print(X_train,Y_train)
#X_test = test_orig.iloc[:,0:10].values
#Y_test = test_orig.iloc[:,10].values
#--scaling--
scale = preprocessing.StandardScaler().fit(X_train)
X_train_new = scale.transform(X_train)
X_test_new = scale.transform(X_test)
#print(X_train_new,X_test_new)

/home/nbuser/anaconda3_501/lib/python3.6/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/home/nbuser/anaconda3_501/lib/python3.6/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/home/nbuser/anaconda3_501/lib/python3.6/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [9]:
#--the neural net--
res = MLPClassifier(hidden_layer_sizes=(1000,1000),max_iter=1000)
res.fit(X_train_new, Y_train.ravel())
pred_res = res.predict(X_test_new)

In [10]:
#--results--
print(confusion_matrix(Y_test,pred_res))
print(classification_report(Y_test,pred_res))
print(accuracy_score(Y_test,pred_res))

[[138  23]
 [ 14 117]]
              precision    recall  f1-score   support

           0       0.91      0.86      0.88       161
           1       0.84      0.89      0.86       131

   micro avg       0.87      0.87      0.87       292
   macro avg       0.87      0.88      0.87       292
weighted avg       0.88      0.87      0.87       292

0.8732876712328768
